version: '3.8'

services:
  landing1:
    build: ./site1
    container_name: landing1
    restart: always
    networks:
      - red-web

  landing2:
    build: ./site2
    container_name: landing2
    restart: always
    networks:
      - red-web

  nginx:
    image: nginx:1.25.2
    container_name: nginx-reverse
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - landing1
      - landing2
    networks:
      - red-web

networks:
  red-web:
    driver: bridge
